#!/bin/bash

function usage() {
	echo "usage example: pgtc -s my_test_db_datadir"
	echo ""
	echo "Options:"
	echo "  -h/--help  Usage"
	echo "  -d/--datadir  Folder for initdb"
	echo "  -s/--start  Launch the cluster"
	echo "  -p/--port  Postgres port"
	echo "  -r/--replica  Also create a streaming replica"
    echo "  -b/--binpath  Use the specified Postgres bin folder (default: /usr/lib/postgresql/11/bin/)"
    echo "  -v/--version  Major version (default: 11)"
	exit 0
}

function ensure_empty_folder {
	if [ -d $1 ]; then
		echo "folder $1 already exists!"
		exit 1
	fi
	mkdir $1
}

if [ "$#" -eq 0 ]; then
  usage
fi

BINPATH=/usr/lib/postgresql/11/bin/
VERSION=11  # important to specify for 12+ due to recovery.conf going away
PORT=${PORT:-5433}

while [ $# -gt 1 ]
do
key="$1"

case $key in
    -h|--help)
    usage
    ;;
    -d|--datadir)
    DATADIR="$2"
    ensure_empty_folder $DATADIR
    shift
    ;;
    -s|--start)
    START=1
    ;;
    -b|--binpath)
    BINPATH="${2}/"
    shift
    ;;
    -r|--replica)
    REPLICA=1
    ;;
    -p|--port)
    PORT="$2"
    shift
    ;;    
    -a|--alias)
    ALIAS=1
    ;;
    -v|--version)
    VERSION="$2"
    shift
    ;;
    *)
    echo "unknown option: $key"
    ;;
esac
shift # past argument or value
done

if [ -n "$1" ]; then
    DATADIR="$1"
fi


echo "running initdb with BINDIR $BINPATH ..."
echo "*** using NON-PERSISTENT settings ***"

${BINPATH}initdb --no-sync --auth-local=trust --auth-host=trust -D $DATADIR &>/dev/null
if [ $? -ne 0 ]; then
	echo "initdb failed"
	exit 1
fi


OPTS=$(cat <<HERE
port=${PORT}
fsync=off
full_page_writes=off
wal_compression=on
unix_socket_directories='/tmp'
logging_collector=on
log_filename='postgresql.log'
max_wal_senders=10
max_replication_slots=10
wal_level=logical
hot_standby=on
cluster_name=pgtc_${PORT}
HERE
)

echo "$OPTS" >> $DATADIR/postgresql.conf
echo ""
echo "Configuration changes applied: "
echo "$OPTS"
echo ""


if [ -n "$REPLICA" ]; then

    echo "setting up a replica ..."

    sed -ri 's/#([local|host].*replication)/\1/g' $DATADIR/pg_hba.conf

    echo "starting master"
    ${BINPATH}pg_ctl -D $DATADIR -w start &>/dev/null
    echo "stopping master again"
    ${BINPATH}pg_ctl -D $DATADIR -w stop &>/dev/null

    # pg_basebackup -D "$DATADIR_repl" start &>/dev/null
    echo "$DATADIR ${DATADIR}_repl"
    cp -r $DATADIR ${DATADIR}_repl
    if [ $? -ne 0 ]; then
        echo "copying replica failed"
        exit 1
    fi
    REPL_PORT=$((PORT+1))
    echo "port=$REPL_PORT" >> ${DATADIR}_repl/postgresql.conf
    echo "cluster_name=pgtc_${REPL_PORT}" >> ${DATADIR}_repl/postgresql.conf

    if [ $VERSION -ge 12 ] ; then
        touch ${DATADIR}_repl/standby.signal
        echo "primary_conninfo='host=localhost port=${PORT} application_name=replica1'" >> ${DATADIR}_repl/postgresql.conf
    else
        echo "standby_mode=on" >> ${DATADIR}_repl/recovery.conf
        echo "primary_conninfo='host=localhost port=${PORT} application_name=replica1'" >> ${DATADIR}_repl/recovery.conf
    fi
    echo "replica in folder ${DATADIR}_repl with port $REPL_PORT created"
fi



if [ -n "$START" ]; then
	echo "starting postgresql on port $PORT ..."
	${BINPATH}pg_ctl -D $DATADIR start &>/dev/null
	if [ $? -ne 0 ]; then
		echo "pg_ctl start failed"
		exit 1
	fi	
    echo "Postgres cluster in folder '${DATADIR}', port ${PORT} started"

    if [ -n "$REPLICA" ]; then
        echo "starting replica on port $REPL_PORT ..."
        ${BINPATH}pg_ctl -D ${DATADIR}_repl start &>/dev/null
        if [ $? -ne 0 ]; then
            echo "pg_ctl start failed"
            exit 1
        fi
        echo "Postgres replica in folder '${DATADIR}_repl', port ${REPL_PORT} started"
    fi
fi

echo ""
echo "Postgres cluster setup in folder '${DATADIR}' finished"
echo ""
echo "Execute below to create aliases pgtc_stop/start/destroy_X"
echo "\". pgtc_aliases $DATADIR\""

if [ -n "$BINPATH" ] ; then
  echo ""
  echo "or"
  echo ""
  echo "${BINPATH}pg_ctl -D ${DATADIR} start"
  if [ -n "$REPLICA" ] ; then
    echo "${BINPATH}pg_ctl -D ${DATADIR}_repl start"
  fi
fi
